pages/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    

]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote', views.vote, name='vote')

]

pollster/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('pages.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls), 
]

pages/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

# Create your models here. i.e. questions and choices here

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pages/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'pages/index.html')

polls/views.py
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Question, Choice


# Get Quesions and display them.

def index (request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

# Show specific questions and choices
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist!")
    return render(request, 'polls/detail.html', {'question': question})

# Get question and display results
def results(request, question_id):
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'polls/results.html', {'question': question})

# Vote for a question choice
def vote(request, question_id):
    # print (request.POST['choice'])
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'polls/detail.html',{
            'question': question,
            'error_message': "You didn't select a choice.",            
        })
    else :
        selected_choice.votes += 1
        selected_choice.save()
        # Always return a HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        <title>Pollster {% block title %}{% endblock %}</title>


    </head>
    <body>
        <!-- NavBar -->
        {% include 'partials/_navbar.html' %}
        <div class="container">
            <div class="row">
                <div class="col-md-6 m-auto">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

templates/pages/index.html
{% extends 'base.html' %}
{% block content %}

<div class="card text-center">
    <div class="card-body">
        <h1>Welcome to Pollster</h1>
        <p>This is an example Django polling app</p>
        <a class="btn btn-dark" href="{% url 'polls:index' %}">
            View Available Polls</a>
    </div>
</div>
{% endblock %}

templates/partials/_navbar.html
<nav class="navbar navbar-dark bg-primary mb-4">
    <div class="container">
        <a class="navbar-brand" href="/">Pollster</a>
    </div>
</nav>

templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-secondary btn-sm mb-3" href="{% url 'polls:index' %}">Back to Polls</a>
<h1 class="text-center mb-3">{{question.question_text}}</h1>

{% if error_message %}
<p class="alert alert-danger">
    <strong>{{ error_message }}</strong>
</p>

{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <div class="form-check">
            <input
                type="radio"
                name="choice"
                class="form-check-input"
                id= "choice{{ forloop.counter }}"
                value="{{choice.id}}"
            />
            <label for="choice{{forloop.counter }}"> {{ choice.choice_text }}</label>
        </div>
    {% endfor %}
    <input type="submit" value="Vote" class="btn btn-success btn-lg btn-block mt-4">

</form> 
{% endblock %}

templates/polls/index.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="text-center mb-3">Poll Questions</h1>
    {% if latest_question_list %}
        {% for question in latest_question_list %}
            <div class="card mb-3">	
                <div class="card-body">
                    <p class="lead">{{ question.question_text }}</p>
                    <a href = "{% url 'polls:detail' question.id %}" class="btn btn-primary btn-sm">Vote Now</a>
                    <a href = "{% url 'polls:results' question.id %}" class="btn btn-secondary btn-sm">Results</a>
                </div>
            </div>        
        {% endfor %}
    {% else %}
        <p> No poll questions available</p>
    {% endif%}
{% endblock %}

templates/polls/results.html
{% extends 'base.html' %}
{% block content %}

<h1 class="mb-5 text-center">{{question.question_text}}</h1>

<ul class="list-group mb-5">
    {% for choice in question.choice_set.all %}
    <li class="list-group-item">
        {{ choice.choice_text }} <span class="badge badge-success float-right">{{ choice.votes }} vote{{choice.votes | pluralize}}</span>
    </li>
    {% endfor %}
</ul>

<a class="btn btn-secondary" href="{% url 'polls:index' %}">Back to Polls</a>
<a class="btn btn-dark" href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}